name = "SeBa"
uuid = "3436b288-4852-497b-a497-0c05a700422f"
authors = ["Caspar Bruenech <c.w.bruenech@pm.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
